---
- hosts: all
  gather_facts: False
  tasks:
    - name: Checkout Powerline fonts
      git:
        repo: https://github.com/powerline/fonts
        dest: ~/git/fonts
        version: "master"
      notify: powerline install

    # - name: Checkout Nerd fonts
    #   git:
    #     repo: https://github.com/ryanoasis/nerd-fonts
    #     dest: ~/git/nerdfonts
    #     version: "master"
    #   notify: nerdfonts install

  handlers:
    - name: powerline install
      shell: ~/git/fonts/install.sh
      args:
        chdir: ~/git/fonts

    # - name: nerdfonts install
    #   shell: ~/git/nerdfonts/install.sh
    #   args:
    #     chdir: ~/git/nerdfonts

# vim:ft=ansible:
