# vim:ft=ansible:
---
- hosts: all
  tasks:
    - name: "Install base packages for Debian-like"
      include_tasks: OSs/debian-full.yml
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: "Install base OSs for Centos"
      include_tasks: OSs/centos-full.yml
      when: ansible_distribution == 'CentOS'

    - name: "Install base OSs for Fedora"
      include_tasks: OSs/fedora-full.yml
      when: ansible_distribution == 'Fedora'

    - name: "Install base OSs for Mac OS X"
      include_tasks: OSs/macosx.yml
      when: ansible_distribution == 'MacOSX'

    - name: "Install base packages for FBSD"
      include_tasks: OSs/freebsd.yml
      when: ansible_distribution == 'FreeBSD'

    - name: Install Neovim
      shell: which nvim 2>/dev/null || ~/bin/install_neovim.sh

    - name: Powerline fonts
      git: repo=https://github.com/powerline/fonts
           dest=~/git/fonts
           force=yes
      register: powerline

    - name: Nerd fonts
      git: repo=https://github.com/ryanoasis/nerd-fonts
           dest=~/git/nerdfonts
           force=yes
      register: nerdfonts

    - name: Install nerdfonts
      shell: ~/git/nerdfonts/install.sh
      args:
        chdir: ~/git/nerdfonts
      when: nerdfonts.changed
      ignore_errors: true

    - name: Install Powerline Fonts
      shell: ~/git/fonts/install.sh
      args:
        chdir: ~/git/fonts
      when: powerline.changed
      ignore_errors: true
