---
- hosts: all
  gather_facts: false
  vars:
    - packages:
        - mccabe
        - yapf
        - pycodestyle==2.3.1
        - isort
        - pep8
        - pep8-naming
        - flake8-coding
        - flake8-imports
        - flake8-requirements
        - powerline-status
        - requests
        - ansible-lint
        - yamllint
        - python-vlc
        - boto3
        - pylint
        - pylama
        - nose
        - nose-cov
        - rednose
        - pytest
        - pytest-cov

  tasks:
    - name: pip-2 modules
      pip:
        executable: pip-2
        name: "{{ packages }}"
        state: present
        extra_args: '-U --user'

    - name: pip-3 modules
      pip:
        executable: pip3
        name: "{{ packages }}"
        state: present
        extra_args: '-U --user'
