# vim:ft=ansible:
---
- hosts: all
  tasks:
    - name: "Install base packages for Debian-like"
      include: packages/servers.yml
      when: ansible_distribution == 'Ubuntu'
    - name: "Ansible configuration"
      file: src={{ playbook_dir }}/files/ansible.cfg.symlink dest=~/.ansible.cfg state=link
    - name: include pip
      include: packages/pip-servers.yml
    - name: "AWS dir"
      file: path=~/.aws state=directory mode=700 force=yes
    - name: "AWS Config"
      file: src={{ playbook_dir }}/files/aws.config.symlink dest=~/.aws/config state=link
    - name: "ctags Config"
      file: src={{ playbook_dir }}/files/ctags.symlink dest=~/.ctags state=link
    - name: "Emacs Config"
      file: src={{ playbook_dir }}/files/emacs.symlink dest=~/.emacs state=link
    - name: "tmux config"
      file: src={{ playbook_dir }}/files/tmux.conf.symlink dest=~/.tmux.conf state=link
    - name: "pylintrc config"
      file: src={{ playbook_dir }}/files/pylintrc.symlink dest=~/.pylintrc state=link
    - name: "gemrc config"
      file: src={{ playbook_dir }}/files/gemrc.symlink dest=~/.gemrc state=link
    - name: "zpreztorc"
      file: src={{ playbook_dir }}/files/zpreztorc.symlink dest=~/.zpreztorc state=link
    - name: "zshrc"
      file: src={{ playbook_dir }}/files/zshrc.symlink dest=~/.zshrc state=link
    - name: "xinitrc"
      file: src={{ playbook_dir }}/files/xinitrc.symlink dest=~/.xinitrc state=link
    - name: "profile"
      file: src={{ playbook_dir }}/files/profile.symlink dest=~/.profile state=link
    - name: "hushlogin"
      file: src={{ playbook_dir }}/files/hushlogin.symlink dest=~/.hushlogin state=link
    - name: "Functions"
      file: src={{ playbook_dir }}/files/functions.symlink dest=~/.functions state=link
    - name: "Alias"
      file: src={{ playbook_dir }}/files/alias.symlink dest=~/.alias state=link
    - name: "Alias git"
      file: src={{ playbook_dir }}/files/alias.git.symlink dest=~/.alias.git state=link
    - name: "git config"
      file: src={{ playbook_dir }}/files/gitconfig.symlink dest=~/.gitconfig state=link
    - name: "User shell"
      user: name={{ansible_user_id}} shell=/bin/zsh
    - name: "Clone prezto zsh"
      git: repo=https://github.com/sorin-ionescu/prezto.git dest=~/.zprezto force=yes
    - name: "Zlogin"
      file: src=~/.zprezto/runcoms/zlogin dest=~/.zlogin state=link
    - name: "Zlogout"
      file: src=~/.zprezto/runcoms/zlogout dest=~/.zlogout state=link
    - name: "Zprofile"
      file: src=~/.zprezto/runcoms/zprofile dest=~/.zprofile state=link
    - name: "Zenv"
      file: src=~/.zprezto/runcoms/zshenv dest=~/.zshenv state=link
    - name: "nvim config dir"
      file: path=~/.config/nvim/autoload state=directory
    - name: "vim plug nvim"
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: ~/.config/nvim/autoload/plug.vim
    - name: "vim config dir"
      file: path=~/.vim/autoload state=directory
    - name: "vim plug vim"
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: ~/.vim/autoload/plug.vim
    - name: "vimrc"
      file: src={{ playbook_dir }}/files/vimrc.symlink dest=~/.vimrc state=link
    - name: "vimrc nvim"
      file: src={{ playbook_dir }}/files/vimrc.symlink dest=~/.config/nvim/init.vim state=link
    - name: "nvim PlugInstall"
      shell: nvim +PlugInstall +qall
