# vim:ft=ansible:
---
- hosts: all
  tasks:

    - name: "Install base packages for Debian-like"
      include: OSs/debian.yml
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: "Install base OSs for Centos"
      include: OSs/centos.yml
      when: ansible_distribution == 'CentOS'

    - name: "Install base OSs for Fedora"
      include: OSs/fedora.yml
      when: ansible_distribution == 'Fedora'

    - name: "Install base OSs for Mac OS X"
      include: OSs/macosx.yml
      when: ansible_distribution == 'MacOSX'

    - name: pip modules
      include: OSs/pip.yml
    - name: "Ansible configuration"
      file: src={{ playbook_dir }}/files/ansible.cfg.symlink dest=~/.ansible.cfg state=link force=yes
    - name: "AWS dir"
      file: path=~/.aws state=directory mode=700 force=yes
    - name: "AWS Config"
      file: src={{ playbook_dir }}/files/aws.config.symlink dest=~/.aws/config state=link force=yes
    - name: "ctags Config"
      file: src={{ playbook_dir }}/files/ctags.symlink dest=~/.ctags state=link force=yes
    - name: "Emacs Config"
      file: src={{ playbook_dir }}/files/emacs.symlink dest=~/.emacs state=link force=yes
    - name: "tmux config"
      file: src={{ playbook_dir }}/files/tmux.conf.symlink dest=~/.tmux.conf state=link force=yes
    - name: "pylintrc config"
      file: src={{ playbook_dir }}/files/pylintrc.symlink dest=~/.pylintrc state=link force=yes
    - name: "gemrc config"
      file: src={{ playbook_dir }}/files/gemrc.symlink dest=~/.gemrc state=link force=yes
    - name: "zpreztorc"
      file: src={{ playbook_dir }}/files/zpreztorc.symlink dest=~/.zpreztorc state=link force=yes
    - name: "zshrc"
      file: src={{ playbook_dir }}/files/zshrc.symlink dest=~/.zshrc state=link force=yes
    - name: "xinitrc"
      file: src={{ playbook_dir }}/files/xinitrc.symlink dest=~/.xinitrc state=link force=yes
    - name: "profile"
      file: src={{ playbook_dir }}/files/profile.symlink dest=~/.profile state=link force=yes
    - name: "hushlogin"
      file: src={{ playbook_dir }}/files/hushlogin.symlink dest=~/.hushlogin state=link force=yes
    - name: "Functions"
      file: src={{ playbook_dir }}/files/functions.symlink dest=~/.functions state=link force=yes
    - name: "Alias"
      file: src={{ playbook_dir }}/files/alias.symlink dest=~/.alias state=link force=yes
    - name: "Alias git"
      file: src={{ playbook_dir }}/files/alias.git.symlink dest=~/.alias.git state=link force=yes
    - name: "Alias hosts"
      file: src={{ playbook_dir }}/files/alias.hosts.symlink dest=~/.alias.hosts state=link force=yes
    - name: "git config"
      file: src={{ playbook_dir }}/files/gitconfig.symlink dest=~/.gitconfig state=link force=yes
    - name: "Clone prezto zsh"
      git: repo=https://github.com/sorin-ionescu/prezto.git dest=~/.zprezto force=yes
    - name: "Zlogin"
      file: src=~/.zprezto/runcoms/zlogin dest=~/.zlogin state=link force=yes
    - name: "Zlogout"
      file: src=~/.zprezto/runcoms/zlogout dest=~/.zlogout state=link force=yes
    - name: "Zprofile"
      file: src=~/.zprezto/runcoms/zprofile dest=~/.zprofile state=link force=yes
    - name: "Zenv"
      file: src=~/.zprezto/runcoms/zshenv dest=~/.zshenv state=link force=yes
    - name: "nvim config dir"
      file: path=~/.config/nvim/autoload state=directory
    - name: "vim plug nvim"
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: ~/.config/nvim/autoload/plug.vim
    - name: "vim config dir"
      file: path=~/.vim/autoload state=directory
    - name: "vim plug vim"
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: ~/.vim/autoload/plug.vim
    - name: "vimrc"
      file: src={{ playbook_dir }}/files/vimrc.symlink dest=~/.vimrc state=link force=yes
    - name: "vimrc nvim"
      file: src={{ playbook_dir }}/files/vimrc.symlink dest=~/.config/nvim/init.vim state=link force=yes
    - name: "vim PlugInstall"
      command: vim +PlugInstall +qall
    - name: "Install gems"
      gem: name={{item}} state=present
      become: true
      with_items:
        - neovim
        - rails
    - name: Clone Nerd fonts
      git: repo=https://github.com/ryanoasis/nerd-fonts
           dest=~/git/nerd-fonts
      register: nerdfont
    - name: Install Nerd Fonts
      shell: ~/git/nerd-fonts/install.sh
      when: nerdfont.changed
